In [6]:
import pandas as pd

df = pd.read_csv('run4191_lightcurve_10bins.csv', sep=' ', header=0)
df.head()

,time,time_err,excess,excess_err,sigma,sigma_err,flux,flux_err,on_counts,off_counts,emin,emax
0,1.616302e+09,58.123744,16.666667,12.884099,2.175926,27.117284,2.250942e-10,1.740081e-10,54.0,112.0,0.03,1.0
1,1.616302e+09,58.123744,3.333333,12.409674,0.461997,685.700732,4.501884e-11,1.676007e-10,41.0,113.0,0.03,1.0
2,1.616302e+09,58.123744,4.333333,12.449900,0.597481,405.897109,5.852449e-11,1.681440e-10,42.0,113.0,0.03,1.0
3,1.616303e+09,58.123744,0.666667,11.401754,0.101102,12619.009649,9.003767e-12,1.539881e-10,33.0,97.0,0.03,1.0
4,1.616302e+09,58.123744,8.000000,12.489996,1.091864,115.087362,1.080452e-10,1.686855e-10,45.0,111.0,0.03,1.0